### ISSUE TITLE
Directory Upload handles index improperly

### ISSUE THREAD

**Issue by imcjohn** [NebulousLabs/skynet-webportal#122]
When you upload an entire directory, and try and browse it like a website, it doesn't put the root of the folder to the index.html file (or other index).

for instance, https://siasky.net/EAByx9EagK71BoS1za93Q9s0l7xSe7VG6P8aUEtJK4mmDQ/build/index.html works, but https://siasky.net/EAByx9EagK71BoS1za93Q9s0l7xSe7VG6P8aUEtJK4mmDQ/build/ has an error rather than redirecting to the index

**Comment by kwypchlo** [comment]
We currently do not support index file discovery as web servers like nginx or apache do. You need to explicitly point the file you want to access.

**Comment by skmendez** [comment]
Would PR's be accepted to make support for index file discovery possible?

**Comment by kwypchlo** [comment]
Of course, you're welcome to submit a PR :)

**Comment by skmendez** [comment]
This is something that is not dealt with by the skynet-webportal, as this just proxies such a request to  `siad`.
