### ISSUE TITLE
Directory Upload will not generate accessible links for filenames containing spaces

### ISSUE THREAD

**Issue by grimmthetallest** [NebulousLabs/skynet-webportal#190]
When attempting to upload a folder via the webportal, the upload will complete successfully but files that would ordinarily require percent-encoding do not seem to be accessible even when attempting to access the proper percent-encoded paths.

Example:

Given a folder containing /folder/file.txt and /folder/my file.txt, the former is accessible at the URL http:// skynet-webportal/skylink/file.txt but the latter is not accessible at the URL http:// skynet-webportal/skylink/my%20file.txt

Please fix the upload of files inside directories that would require percent-encoded paths for retrieval when using the proper percent-encoded HTTP path.

A list of encoded characters and relevant RFCs can be found here: https://en.wikipedia.org/wiki/Percent-encoding

**Comment by kwypchlo** [comment]
Thank you for the report @grimmthetallest 👍  I'll make sure it's being taken care of.

**Comment by kwypchlo** [comment]
verification https://siasky.net/AABSym8Pet0XPm2z260JY2cbYv0GjtyhhFm8EldKmeP1pg/b%20b%20b/c%20c%20c.txt
