### ISSUE TITLE
Filenames not handled correctly

### ISSUE THREAD

**Issue by MSevey** [NebulousLabs/skynet-webportal#203]
I'm seeing the filenames not being handled properly when uploading through the portal.  Seems like both dragging and dropping are not preserving the filename as it is on disk.

**Comment by kwypchlo** [comment]
@MSevey can you share an example link that contains a mislabeled file? What was the original name? What is the browser you are using?

**Comment by MSevey** [comment]
might be a david thing, he told me about it and I couldn't repro. Might have been due to siad crashing at the same time. 

Closing for now.
