### ISSUE TITLE
Ubuntu setup.sh: Package 'python-certbot-nginx' has no installation candidate

### ISSUE THREAD

**Issue by DaWe35** [NebulousLabs/skynet-webportal#216]
`./setup.sh`
![kép](https://user-images.githubusercontent.com/10603822/82676596-f331ea80-9c46-11ea-8a0a-b40c0bace5b5.png)

I think Skynet needs to install `python3-certbot-nginx` on Ubuntu

**Comment by kwypchlo** [comment]
Thanks for the report @DaWe35 but I am going to put that ticket on hold because I have an architecture rewrite incoming that will make this obsolete.
