### ISSUE TITLE
Warn users about 3-month default pin-time

### ISSUE THREAD

**Issue by DaWe35** [NebulousLabs/skynet-webportal#217]
I think it is necessary to warn new Skynet users that their files can be deleted in 3 months. A lot of users will experience that Skynet is not reliable, because they will see 404 error. Why it is not mentioned on the main page? We need to make it very clear.

**Comment by kwypchlo** [comment]
@DavidVorick can you chime in?

**Comment by DavidVorick** [comment]
We will add more notices about the free tier once we have the premium tier set up.
