### ISSUE TITLE
Improve upload error reporting

### ISSUE THREAD

**Issue by kwypchlo** [NebulousLabs/skynet-webportal#230]
We should improve error reporting when uploading. Couple of cases to cover:
- 502 Bad Gateway - most likely issue with siad instance not reachable from web server
- 1GB upload limit - we should cover that on the client side and not even start uploading

I will be extending this list with any other errors that we might report to the user.

Closes #229

**Comment by DaWe35** [comment]
Checking file size in browser could save some bandwidth and time
