### ISSUE TITLE
Wrong Nginx config generated by certbot

### ISSUE THREAD

**Issue by DaWe35** [NebulousLabs/skynet-webportal#235]
Firefox shows me: `PR_END_OF_FILE_ERROR`

Wrong and fixed config: https://gist.github.com/DaWe35/e06615f979a8422a1d5f114077f34338/revisions

Skynet portal server OS: Debian 10.4

**Comment by kwypchlo** [comment]
Thanks for the report @DaWe35 but I am going to put that ticket on hold because I have an architecture rewrite incoming that will make this obsolete.

**Comment by DaWe35** [comment]
> Thanks for the report @DaWe35 but I am going to put that ticket on hold because I have an architecture rewrite incoming that will make this obsolete.

Ahh okay, of course, cool
