### ISSUE TITLE
Requests timing out

### ISSUE THREAD

**Issue by drmathias** [NebulousLabs/skynet-webportal#243]
When trying to access skylinks through some of the public portals, occasionally I will receive the following response.

> {"message":"failed to fetch skylink: [unable to fetch base sector of skylink; unable to fetch sector root from the network; workers were unable to recover the data by sector root - all workers failed; [timed out after 30s; project timed out]]"}

Will get the same message through [siasky.net](https://siasky.net), [siacdn.com](https://siacdn.com) and [skynethub.io](https://skynethub.io), so it seems to affect all of the public portals at once. The problem persists and you won't be able to access files for several minutes.

**Comment by saumyabratadutt** [comment]
Yes, same here. I tried opening some links and it doesn't work.

**Comment by kwypchlo** [comment]
We are experiencing heavy load on all the portals. Once new minor siad version is released and portal operators upgrade their nodes, it should improve the situation immensely. Until then you can always download the files through your sia node if you experience issues with the public ones. Sorry for the inconvenience, I will leave this issue stay open until the improvements are in place.

**Comment by kwypchlo** [comment]
I think I can close this one already. We've improved the portal infrastructure and released numerous siad performance improvements. Feel free to open up the issue again if the problem comes back. Thank you!
