### ISSUE TITLE
Timeout attempting to retrieve an uploaded directory

### ISSUE THREAD

**Issue by DotNetRussell** [NebulousLabs/skynet-webportal#259]
Problem Synopsis:
I attempted to deploy a simple test website directory to skynet. It seems to have uploaded fine via the https://siasky.net/ directory upload portal but upon retrieval there's a timeout. 

The site I attempted to upload (minus the git files) https://github.com/DotNetRussell/arussellrentals

The skylink that was generated for me is https://siasky.net/_AVZCZjaR0sWvfyXXB8dy5HvDQtEtwlypRTQHtSHepxTBw 

The server response is 404 and the resulting error text is 

`[{"message":"failed to fetch skylink: [unable to fetch base sector of skylink; timed out after 30s; project timed out; workers were unable to recover the data by sector root - all workers failed]"}]`

My assumption of what is happening is that while it's in the middle of retrieving data the timeout limit is hit and it kills it mid stream. I believe this because when I attempt to navigate to that skylink, sometimes, the background will turn black which would only happen if something was being returned.

**Comment by kwypchlo** [comment]
Thank you for the report @DotNetRussell - we already have an issue https://github.com/NebulousLabs/skynet-webportal/issues/243 for that so I will go ahead and reference this one there.
