### ISSUE TITLE
JavaScript: Refused to get unsafe header "skynet-file-metadata"

### ISSUE THREAD

**Issue by Kcchouette** [NebulousLabs/skynet-webportal#306]
On chromium browser, I have this kind of log:
```
JavaScript: Refused to get unsafe header "skynet-file-metadata"
```

It seems it can be fixed by adding that on nginx conf:
```
'Access-Control-Expose-Headers' 'skynet-file-metadata';
```

This error is because when the header is non-standard and not put as exposed, it prints an “non-error” message into the console, and no execution is stopped.

The problem occurs on siasky.net / siasky.dev and skyportal.xyz

portal siacdn.com, skydrain.net, skynethub.io works fine

Cheers

**Comment by kwypchlo** [comment]
Closed by #307
