### ISSUE TITLE
HNS subdomains

### ISSUE THREAD

**Issue by peterjanbrone** [NebulousLabs/skynet-webportal#421]
F/U this should probably be able to handle `some-domain.hns.germany.siasky.net`

_Originally posted by @peterjanbrone in https://github.com/NebulousLabs/skynet-webportal/pull/420#r494364594_

**Comment by Delivator** [comment]
Not sure what this issue is for, but in [setup-scripts#wildcard-ssl-certificate](https://github.com/NebulousLabs/skynet-webportal/tree/master/setup-scripts#wildcard-ssl-certificate) it should probably also be mentioned that you also need `*.hns.domain.tld` in the Caddyfile for proper support.
