### ISSUE TITLE
Handshake emoji domains return "Handshake error: Invalid name." on /hnsres/

### ISSUE THREAD

**Issue by Delivator** [NebulousLabs/skynet-webportal#458]
The handshake-api package returns `Handshake error: Invalid name.` when trying to resolve emoji domains.

Example: https://siasky.net/hnsres/😈😈😈

**Comment by kwypchlo** [comment]
Thanks for the report, I will look into that 👍

**Comment by Delivator** [comment]
Dang it, I think I messed the title up again so it didn't auto close this issue 😬

**Comment by kwypchlo** [comment]
Closed by #470
