### ISSUE TITLE
504 Gateway Time-out from registry when file doesn't exist

### ISSUE THREAD

**Issue by kamy22** [NebulousLabs/skynet-webportal#492]
```
...
import { SkynetClient, SkyFile, FileID, User, FileType } from "skynet-js";
...

const skynetClient = new SkynetClient("https://siasky.net");
const filename = "test.txt";
const fileID = new FileID("testapp", FileType.PublicUnencrypted, filename);

const user = new User("test","test");
const skyFile = await skynetClient.getFile(user, fileID);
```

When I try to get a file that doesn't exist, the call to the registry returns a 504 Gateway Time-out error instead of returning 404. To reproduce the error, you can just try the link:

[https://siasky.net/skynet/registry?publickey=ed25519%3Ae67bb41e791ed805160f016f42627887f6a9f1769a51587761ece5d64ddab455&fileid=7b2276657273696f6e223a312c226170706c69636174696f6e6964223a2274657374617070222c2266696c6574797065223a312c2266696c656e616d65223a22746573742e747874227d](https://siasky.net/skynet/registry?publickey=ed25519%3Ae67bb41e791ed805160f016f42627887f6a9f1769a51587761ece5d64ddab455&fileid=7b2276657273696f6e223a312c226170706c69636174696f6e6964223a2274657374617070222c2266696c6574797065223a312c2266696c656e616d65223a22746573742e747874227d)

**Comment by kamy22** [comment]
@kwypchlo @ChrisSchinnerl I think the mentioned issue doesn’t solve the problem. It seems to be a more serious bug. Try to use https://siasky.net/_BF4CHsFIichxjdgAFhU-tEKqsoPDxC9OMsWbMkyMbz4KQ/ with a non-existent user. The service should check if the `note.txt` file exists. If there is no such file, it should create a new one.

The problem here is that **skynet/registry** doesn't work as expected. When a file is not present it should return a 404 error. Now the registry timeouts and the **Make Note service** works just because the timeout error is caught.

<img width="1181" alt="Screenshot 2020-10-26 at 15 49 26" src="https://user-images.githubusercontent.com/1657091/97188189-87c6e880-17a3-11eb-974d-13c99b531931.png">

**Comment by kwypchlo** [comment]
We will be deploying siasky.net with a fix early this week.
