### ISSUE TITLE
Resolve Folder to index.html if available

### ISSUE THREAD

**Issue by m-cat** [NebulousLabs/skynet-webportal#569]
Right now, urls to folders don't serve the index.html but instead try to download a .zip of the folder.

https://oklacity.hns.siasky.net/other/index.html vs https://oklacity.hns.siasky.net/other/

**Comment by kwypchlo** [comment]
This is on the siad side, index.html resolving only works on the top level of the uploaded directory due to limitations at the time of implementing this feature. Please submit the issue on https://gitlab.com/NebulousLabs/Sia
