### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by peterjanbrone** [NebulousLabs/skynet-webportal#87]
We should properly enable CORS and remove it from siad.  Issue already created there. Perhaps look at https://enable-cors.org/server_nginx.html for inspiration. Created issue in order we do not forget.

**Comment by kwypchlo** [comment]
I don't see cors being removed from siad any time soon but https://github.com/NebulousLabs/skynet-webportal/pull/231 should resolve any issues we had with cors now.
